#!/bin/bash

clear
cat conf/head.txt
make


echo ----------- CORNELIA INSTALLED OK ------------
echo Please set CORNELIA_HOME to cornelia base dir. ie. export CORNELIA_HOME=$(pwd)
echo Start Cornelia: bin/startup.sh
echo Stop Cornelia: bin/shutdown.sh


